In [1]:
# Import the necessary modules
import SciServer
from SciServer import SkyServer
import matplotlib.pyplot as plt
from astropy.io import ascii, fits
from astropy.table import Table
import numpy as np

/home/fortson/manth145/.conda/envs/tf_latest/lib/python3.9/site-packages/skimage/io/manage_plugins.py:23: UserWarning: Your installed pillow version is < 8.1.2. Several security issues (CVE-2021-27921, CVE-2021-25290, CVE-2021-25291, CVE-2021-25293, and more) have been fixed in pillow 8.1.2 or higher. We recommend to upgrade this library.
  from .collection import imread_collection_wrapper


In [2]:
data_file = fits.getdata('/home/fortson/manth145/data/Misc/LEAM/LEAM_sample.fits')

In [3]:
queried_table = Table(names=['ID', 'RA', 'DEC', 'ObjID', 'SpecObjID', 'logM', 'Z', 'Age', 'sSFR', 'halpha_flux'],
                     dtype=['str', 'float', 'float', 'int', 'int', 'float', 'float','float', 'float', 'float'])

In [5]:
len(data_file)

82

In [4]:
# If the info you are providing is a tuple of (RA, DEC) positions, then use the following. Load a catalog and pass a list of tuples to iteratively 
# fetch the images.
info_type ='ra_dec'

'''
If you have ObjIDs (unique to each data release), then comment the above and use the following.
'''
# info = [1237671932283322445]
# info_type ='ID'

obj_info_search_DR = "DR16" # Data release to be used to query the ObjID, PetroR90 information
image_data_release = "DR7" # Data release from which the Jpeg should be queried.


for each_info in data_file: #iterate over the loop

    ra, dec = (each_info['RA'], each_info['DEC']) #unpack the RA and DEC info

    object_search_data =  SciServer.SkyServer.objectSearch(ra= ra, dec = dec, dataRelease=obj_info_search_DR) # Query the object information
    object_id = object_search_data[0]['Rows'][0]['objId'] # grab the ObjID 
    spec_obj_id = object_search_data[0]['Rows'][0]['specObjId']
    if spec_obj_id !='' and object_id!= '':
    #     sql_query = "SELECT p.ra, p.dec, p.ObjID, p.PetroR90_r from PhotoPrimary p WHERE p.objID = %s"%(object_id) # set up SQL query to retrieve PetroR50_r
        spec_query = "SELECT g.h_alpha_flux from galSpecLine g WHERE g.specObjID = %s"%(spec_obj_id)
        stellar_mass_query = "SELECT m.logMass, m.metallicity, m.age, m.ssfr from stellarMassFSPSGranWideDust m WHERE m.specObjID = %s"%(spec_obj_id)
    #     queried_data = SciServer.SkyServer.sqlSearch(sql_query, dataRelease=obj_info_search_DR) # queried data
        try:
            spec_queried_data = SciServer.SkyServer.sqlSearch(spec_query, dataRelease=obj_info_search_DR).to_numpy()[0]
        except IndexError:
            spec_queried_data = np.array([-99])
        
        try:
            physical_properties = SciServer.SkyServer.sqlSearch(stellar_mass_query, dataRelease=obj_info_search_DR).to_numpy()[0]
        except IndexError:
            physical_properties = np.array([-99, -99, -99, -99])

        queried_table.add_row(np.concatenate([[each_info['ID']], [each_info['RA']], [each_info['DEC']],[object_id], [spec_obj_id], physical_properties, spec_queried_data]))
    else:
        if object_id == '':
            object_id = -99
        queried_table.add_row(np.concatenate([[each_info['ID']], [each_info['RA']], [each_info['DEC']],[object_id], [-99], [-99,-99,-99,-99], [-99]]))


/home/fortson/manth145/.conda/envs/tf_latest/lib/python3.9/site-packages/SciServer-2.1.0-py3.9.egg/SciServer/SkyServer.py:331: Warning: In Authentication.getToken: Authentication token is not defined: the user did not log in with the Authentication.login function, or the token has not been stored in the command line argument --ident.
/home/fortson/manth145/.conda/envs/tf_latest/lib/python3.9/site-packages/SciServer-2.1.0-py3.9.egg/SciServer/SkyServer.py:47: Warning: In Authentication.getToken: Authentication token is not defined: the user did not log in with the Authentication.login function, or the token has not been stored in the command line argument --ident.
/home/fortson/manth145/.conda/envs/tf_latest/lib/python3.9/site-packages/SciServer-2.1.0-py3.9.egg/SciServer/SkyServer.py:47: Warning: In Authentication.getToken: Authentication token is not defined: the user did not log in with the Authentication.login function, or the token has not been stored in the command line argument --i

In [8]:
object_id

''

In [6]:
ascii.write(queried_table, '/home/fortson/manth145/data/Misc/LEAM/Leam_Sample_SDSS_Info.csv', format='csv', overwrite=True)

In [5]:
queried_table

<Table length=82>
      ID              RA         ...        sSFR        halpha_flux
    str16          float64       ...      float64         float64  
------------- ------------------ ... ------------------ -----------
   dm1152+07a 178.12779166666667 ... -0.282896220684052    66.54812
   dm1152+07b          178.12525 ... -0.285143464803696    1625.038
   dm0035-10a  8.951291666666666 ...              -99.0       -99.0
   dm0035-10b  8.951166666666667 ...              -99.0       -99.0
   dm1059+47a 164.77733333333333 ... -0.699218332767487    114.7458
   dm1059+47b  164.7697083333333 ... -0.521150290966034    421.3619
   dm1142+52a         175.754375 ...  -0.29055792093277    32.60795
   dm1142+52b         175.739125 ...  -1.04490375518799     1206.64
   dm1403+41a 210.80729166666666 ... -0.285143464803696    782.7853
   dm1403+41b            210.804 ... -0.299360185861588      260.67
          ...                ... ...                ...         ...
GPJ0213+0056a        33.27756405 ... -0.285143464803696    3053.005
GPJ0213+0056b        33.27607102 ... -0.299360185861588     49.1058
      IC2058a          64.476458 ...              -99.0       -99.0
      IC2058b          64.529833 ...              -99.0       -99.0
     NGC4532a         188.580542 ...              -99.0       -99.0
     NGC4532b          188.68875 ...              -99.0       -99.0
     NGC3448a         163.663333 ...              -99.0       -99.0
     NGC3448b         163.553152 ... -0.285143464803696    786.9509
     UGC9562a         222.810048 ... -0.806965410709381     1307.04
     UGC9562b         222.735394 ...              -99.0     21246.9

In [8]:
object_search_data[0]['Rows'][0]

{'objId': '1237652948529512701',
 'specObjId': '',
 'apid': '',
 'id': 1237652948529512701,
 'specId': None,
 'name': ''}

In [20]:
np.array(spec_queried_data)

array([[66.54812 ,  2.522923]])

In [22]:
spec_queried_data['h_alpha_flux'][0]

66.54812

In [6]:
physical_properties.to_numpy()[0]

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [27]:
physical_properties

logMass  metallicity      age      ssfr
0  9.481586       0.0077  6.58356 -1.096489

In [17]:
spec_queried_data

array([66.54812])

In [16]:
physical_properties

array([ 9.48158557e+00,  7.69999996e-03,  6.58355951e+00, -1.09648907e+00])

In [25]:
np.concatenate([[each_info['ID']], [each_info['RA']], [each_info['DEC']],[object_id], [spec_obj_id], physical_properties, spec_queried_data])

array(['dm1152+07a', '178.12779166666667', '7.117361111111111',
       '1237661971182583838', '1825092052086450176', '9.48158557056236',
       '0.0076999999582767', '6.58355951309204', '-1.09648907184601',
       '66.54812'], dtype='<U32')

In [19]:
physical_properties.ravel()

array([ 9.48158557e+00,  7.69999996e-03,  6.58355951e+00, -1.09648907e+00])

In [27]:
queried_table

<Table length=1>
    ID             RA         ...        sSFR       halpha_flux
  str10         float64       ...      float64        float64  
---------- ------------------ ... ----------------- -----------
dm1152+07a 178.12779166666667 ... -1.09648907184601    66.54812